[package]
name = "p-project-contracts"
version = "0.1.0"
edition = "2021"

[dependencies]
p-project-core = { path = "../p-project-core" }
serde.workspace = true
chrono.workspace = true
md5.workspace = true