apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# All resources will be created in this namespace
namespace: p-project

resources:
  - namespace.yaml
  - api.yaml
  - web.yaml
  - bridge-relayer.yaml
  - airdrop-cronjob.yaml
  - ingress.yaml

