[package]
name = "p-project-api"
version = "0.1.0"
edition = "2021"

[dependencies]
p-project-core = { path = "../p-project-core" }
p-project-contracts = { path = "../p-project-contracts" }
serde.workspace = true
tokio.workspace = true
axum = "0.7"
tower-http = { version = "0.5", features = ["cors"] }
serde_json = "1.0"