[package]
name = "p_project_staking"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "~1.10.0"

[dev-dependencies]
solana-program-test = "~1.10.0"
solana-sdk = "~1.10.0"

[lib]
crate-type = ["cdylib", "rlib"]